apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: docker-k8s-demo
spec:
  selector:
    matchLabels:
      run: docker-k8s-demo
  replicas: 2
  template:
    metadata:
      labels:
        run: docker-k8s-demo
    spec:
      containers:
      - name: docker-app
        image: docker-k8s-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo
  labels:
    run: docker-k8s-demo
spec:
#  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: docker-k8s-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-k8s-demo-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: docker-k8s-demo
              servicePort: 3000
